version: '3.7'

services:
  mongo:
    container_name: mongoDB
    image: mongo
    ports:
      -27017:27017
    volumes:
      -mongo_data_container :/data/db
    networks:
      - mongo_network
  express_app:
    container_name: express_app_container
    build: 
      dockerfile: ./Dockerfile
      context: .
    ports:
      -${PORT}:${PORT}
    env_file:
      - .env.compose
    depends_on:
      - mongo
    networks:
      - mongo_network
    command: npm run start
  
volumes:
 mongo_data_container:

networks:
  mongo_network:
    driver: bridge