paths:
  /api/products/:
    get:
      security:
        - cookieAuth: []
      summary: Obtiene una página renderizada con todos los productos
      tags:
        - Products
      responses:
        '200':
          description: Los productos fueron obtenidos satisfactoriamente de la base de datos. Se devuelve una página renderizada con los valores del ejemplo.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        '400':
          description: Error por parte del cliente. Probablemente por no estar logueado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: El estado de la respuesta
                    example: error
                  error:
                    example: "Debe iniciar sesión nuevamente"
        '500':
          description: Error interno del servidor. Usualmente generado por una query defectuosa o una falla con la conexión con la base de datos
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: El estado de la respuesta
                    example: error
                  error:
                    example: "Unhandled error"
    post:
      summary: Crea un producto
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/createProduct'
      responses:
        '200':
          description: El producto fue creado satisfactoriamente en la base de datos
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: El estado de la respuesta
                    value: success
                    example: success
                  payload:
                    $ref: '#/components/schemas/Products'
        '400':
          description: Error por parte del cliente. Probablemente por no estar logueado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: El estado de la respuesta
                    example: error
                  error:
                    example: "Debe iniciar sesión nuevamente"
        '500':
          description: Error interno del servidor. Usualmente generado por una query defectuosa o una falla con la conexión con la base de datos
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: El estado de la respuesta
                    example: error
                  error:
                    example: "Unhanddled error"
  /api/products/{id}:
    get:
      summary: Obtiene un producto
      tags:
        - Products
      parameters:
        - name: id
          in: path
          description: El id del producto
          required: true
          schema:
            type: string
      responses:
        '200':
          description: El producto fue obtenido satisfactoriamente de la base de datos se devuelve pagina renderizada con los valores del example.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        '400':
          description: Error por parte del cliente. Probablemente por no estar logueado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: El estado de la respuesta
                    example: error
                  error:
                    example: "Debe iniciar sesión nuevamente"
        '500':
          description: Error interno del servidor. Usualmente generado por una query defectuosa o una falla con la conexión con la base de datos
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: El estado de la respuesta
                    example: error
                  error:
                    example: "Unhandled error"
    put:
      summary: Actualiza un producto
      tags:
        - Products
      parameters:
        - name: id
          in: path
          description: El id del producto
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/updateProduct'
            example:
              status: "false"
      responses:
        '200':
          description: El producto fue actualizado satisfactoriamente de la base de datos
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Products'
        '400':
          description: Error por parte del cliente. Probablemente por no estar logueado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: El estado de la respuesta
                    example: error
                  error:
                    example: "Debe iniciar sesión nuevamente"
        '500':
          description: Error interno del servidor. Usualmente generado por una query defectuosa o una falla con la conexión con la base de datos
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: El estado de la respuesta
                    example: error
                  error:
                    example: "Unhandled error"
    delete:
      summary: Elimina un producto
      tags:
        - Products
      parameters:
        - name: id
          in: path
          description: El id del producto
          required: true
          schema:
            type: string
      responses:
        '200':
          description: El producto fue eliminado satisfactoriamente de la base de datos
          content:
            application/json:
              schema:
                type: string
                example: Se elimino el producto
        '400':
          description: Error por parte del cliente. Probablemente por no estar logueado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: El estado de la respuesta
                    example: error
                  error:
                    example: "Debe iniciar sesión nuevamente"
        '500':
          description: Error interno del servidor. Usualmente generado por una query defectuosa o una falla con la conexión con la base de datos
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: El estado de la respuesta
                    example: error
                  error:
                    example: "Unhandled error"
components:
  schemas:
    Products:
      type: object
      properties:
        _id:
          type: string
          description: El id del producto
          example: '9385092jtr934'
        title:
          type: string
          description: El nombre del libro
          example: El sabueso de los Baskerville
        thumbnail:
          type: array
          description: Imagen del producto
          example: '["amor en los tiempos.jpg"]'
        price:
          type: number
          description: Precio del producto
          example: 3000
        stock:
          type: number
          description: Stock del producto
          example: 49
        status:
          type: boolean
          description: Estado del producto
          example: true
        category:
          type: string
          description: Categoría del producto
          example: TERROR
        code:
          type: string
          description: Código del producto
          example: '834u'
        description:
          type: string
          description: Descripción del producto
          example: Libro Completo
        owner:
          type: string
          description: Email de quien subió el producto
          example: pepe@hotmail.com
      example:
        _id: 9374293jri2349
        title: El sabueso de los Baskerville
        thumbnail: '["El sabueso de los Baskerville.jpg"]'
        price: 3000
        stock: 49
        status: true
        category: Libro Completo
        owner: pepe@hotmail.com
  requestBodies:
    updateProduct:
      type: object
      required: true
      properties:
        example:
          status: false
    createProduct:
      type: object
      required:
        -Title
        -Category
        -Code
        -Stock
        -Description
        -Thumbnail
        -Price
      properties:
        title:
          type: string
          description: El nombre del libro
          example: El sabueso de los Baskerville
        thumbnail:
          type: array
          description: Imagen del producto
          example: '["amor en los tiempos.jpg"]'
        price:
          type: number
          description: Precio del producto
          example: 3000
        stock:
          type: number
          description: Stock del producto
          example: 49
        status:
          type: boolean
          description: Estado del producto
          example: true
        category:
          type: string
          description: Categoría del producto
          example: TERROR
        code:
          type: string
          description: Código del producto
          example: '834u'
        description:
          type: string
          description: Descripción del producto
          example: Libro Completo
        owner:
          type: string
          description: Email de quien subió el producto
          example: pepe@hotmail.com
      example:
        title: El sabueso de los Baskerville
        thumbnail: '["El sabueso de los Baskerville.jpg"]'
        price: 3000
        stock: 49
        status: true
        category: Libro Completo
        owner: pepe@hotmail.com
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: ['AUTH']
  security:
    - cookieAuth: []  
